apiVersion: v2
name: kubed
description: A Helm chart for kubed for Capact installation

type: application

version: 0.5.0

dependencies:
  - name: kubed
    version: "0.12.0"
    repository: https://charts.appscode.com/stable/
    condition: kubed.enabled
