ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: config
  prefix: cap.type.productivity.confluence
  displayName: Confluence instance config
  description: Defines configuration for Confluence instance
  documentationURL: https://support.atlassian.com/confluence-cloud/
  supportURL: https://www.atlassian.com/software/confluence
  iconURL: https://wac-cdn.atlassian.com/dam/jcr:d6e2d2db-e58a-40f7-9d1a-d6d22a335c96/Confluence-blue.svg
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for Jira configuration",
        "required": [
            "version"
        ],
        "$ocfRefs": {
          "semVer": {
            "name": "cap.core.type.versioning.semver",
            "revision": "0.1.0"
          }
          "hostname": {
            "name": "cap.core.type.networking.hostname",
            "revision": "0.1.0"
          }
        },
        "properties": {
          "version": {
            "$ref": "#/$ocfRefs/semVer"
          }
          "host": {
            "$ref": "#/$ocfRefs/hostname"
          }
        },
        "additionalProperties": true
      }

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
