apiVersion: v2
name: neo4j
description: A Helm chart for neo4j for Capact installation

type: application

version: 0.5.0

dependencies:
  - name: neo4j
    version: "v4.2.0-1"
    repository: https://neo4j-contrib.github.io/neo4j-helm/
    condition: neo4j.enabled
