ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: cap.interface.runner.helm # Computed during fetching the manifest
  name: run
  displayName: "Run"
  description: "Run action for Helm Runner"
  documentationURL: https://projectvoltron.dev
  supportURL: https://projectvoltron.dev
  maintainers:
    - email: team-dev@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev

spec:
  input:
    parameters:
      jsonSchema:
        value: |-
          {
            "$schema": "http://json-schema.org/draft-07/schema",
            "$ocfRefs": {
              "inputType": {
                "name": "cap.type.runner.helm.run-input",
                "revision": "0.1.0"
              }
            },
            "allOf": [ { "$ref": "#/$ocfRefs/inputType" } ]
          }
  output:
    typeInstances:
      helm-release:
        typeRef:
          path: cap.type.helm.chart.release
          revision: 0.1.0
      additional: # Maybe this could be more restricted after split `run` into `install`, `upgrade`, `uninstall`
        typeRef:
          path: cap.core.type.generic.value
          revision: 0.0.1

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
