name: Build image and chart

on:
  workflow_dispatch:
  push:
    paths:
      - "**.go"
      - "**.py"
      - "go.mod"
      - "go.sum"
      - "**.graphql"
      - ".github/workflows/**"
      - "**.sh"
      - "Makefile"
      - "deploy/**"
      - "hub-js/**"
      - "Dockerfile"
      - "!**.md"
      - "**.yaml.tmpl"
    tags:
      - 'v**'

jobs:
  # entry-tests:
  #   name: Lint and test code
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Setup environment
  #       run: |
  #         . ./hack/ci/setup-env.sh
  #     - name: Setup Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: ${{env.GO_VERSION}}
  #     - name: Run linting
  #       run: |
  #         make test-lint
  #       env:
  #         SKIP_GOLANGCI_LINT: true
  #     - name: Run unit tests
  #       run: make test-unit
  #     - name: Check generated files
  #       run: |
  #         make gen-go-api-from-ocf-spec
  #         make gen-k8s-resources
  #         make gen-graphql-resources
  #         make gen-go-source-code
  #         make gen-docs
  #       env:
  #         SKIP_DEPS_INSTALLATION: false

  # golangci-lint:
  #   name: Lint Go code
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Setup environment
  #       run: |
  #         . ./hack/ci/setup-env.sh
  #     - name: Setup Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: ${{env.GO_VERSION}}
  #     - name: Run golangci-lint
  #       uses: golangci/golangci-lint-action@v3.1.0
  #       with:
  #         version: ${{env.GOLANGCI_LINT_VERSION}}
  #         args: --timeout=${{env.GOLANGCI_LINT_TIMEOUT}}

  prepare-matrix:
    name: Prepare components build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix-app: ${{ steps.set-matrix-app.outputs.matrix }}
      matrix-test: ${{ steps.set-matrix-test.outputs.matrix }}
      matrix-infra: ${{ steps.set-matrix-infra.outputs.matrix }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # To be able to compare with the previous commit and detect changed files
      - name: setup env
        run: . ./hack/ci/setup-env.sh
      - id: set-matrix-app
        run: echo "::set-output ${APPS}"
      - id: set-matrix-test
        run: echo "::set-output ${TESTS}"
      - id: set-matrix-infra
        run: echo "::set-output ${INFRAS}"

  build-app:
    name: Build ${{ matrix.APP }}
    runs-on: ubuntu-latest
    needs: prepare-matrix
    strategy:
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix-app)}}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup environment
        run: |
          . ./hack/ci/setup-env.sh
      - name: Set DOCKER_TAG for release
        run: |
          echo "DOCKER_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/v')
      - run: make build-app-image-${{ matrix.APP }}
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - run: make push-app-image-${{ matrix.APP }}

  build-tests:
    name: Build ${{ matrix.TEST }}
    runs-on: ubuntu-latest
    needs: prepare-matrix
    strategy:
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix-test)}}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup environment
        run: |
          . ./hack/ci/setup-env.sh
      - name: Set DOCKER_TAG for release
        run: |
          echo "DOCKER_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/v')
      - run: make build-test-image-${{ matrix.TEST }}
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - run: make push-test-image-${{ matrix.TEST }}

  build-infra:
    name: Build ${{ matrix.INFRA }}
    runs-on: ubuntu-latest
    needs: prepare-matrix
    if: needs.prepare-matrix.outputs.matrix-infra != ''
    strategy:
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix-infra)}}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup environment
        run: |
          . ./hack/ci/setup-env.sh
      - name: Set DOCKER_TAG for release
        run: |
          echo "DOCKER_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/v')
      - run: make build-infra-image-${{ matrix.INFRA }}
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - run: make push-infra-image-${{ matrix.INFRA }}

  release-helm-chart:
    name: Release Helm Charts
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # To be able to compare with the previous commit and detect changed files
      - name: Disable git push
        run: |
          git remote set-url --push origin no_push
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Release Helm Charts if were changed
        env:
          MAIN_BUILD: "true"
        run: |
          make release-charts

  release-cli:
    name: Release the latest Capact CLIs
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup environment
        run: |
          . ./hack/ci/setup-env.sh
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          create_credentials_file: true
          cleanup_credentials: true
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Install upx 3.96
        run: |
          wget https://github.com/upx/upx/releases/download/v4.0.1/upx-4.0.1-amd64_linux.tar.xz
          tar -xf upx-*-amd64_linux.tar.xz
          mv ./upx-*-amd64_linux/upx /usr/local/bin/upx
          upx -V
      - name: Set up GoReleaser
        # run: go install github.com/goreleaser/goreleaser@latest
        run: sudo snap install --classic goreleaser
      - name: Disable git push
        run: |
          git remote set-url --push origin no_push
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Release latest CLI
        run: |
          make release-latest-binaries

  # local-hub-tests:
  #   name: Local Hub integration tests
  #   runs-on: ubuntu-latest
  #   needs: [ entry-tests, build-app, build-tests ]
  #   permissions:
  #     contents: read
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Setup environment
  #       run: |
  #         . ./hack/ci/setup-env.sh
  #     - id: 'auth'
  #       name: 'Authenticate to Google Cloud'
  #       uses: 'google-github-actions/auth@v1'
  #       with:
  #         token_format: 'access_token'
  #         credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
  #     - name: Login to GCR
  #       uses: docker/login-action@v2
  #       with:
  #         registry: gcr.io
  #         username: oauth2accesstoken
  #         password: ${{ steps.auth.outputs.access_token }}
  #     - name: Run local Hub integration tests
  #       env:
  #         BUILD_IMAGES: "false"
  #       run: |
  #         make test-local-hub

  # integration-tests:
  #   name: Integration tests
  #   runs-on: ubuntu-latest
  #   needs: [ entry-tests, build-app, build-tests ]
  #   strategy:
  #     matrix:
  #       cluster: [ kind, k3d ]
  #   permissions:
  #     contents: read
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Setup environment
  #       run: |
  #         . ./hack/ci/setup-env.sh
  #     - name: Setup Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: ${{env.GO_VERSION}}
  #     - name: Run K8s Controller integration tests
  #       run: |
  #         make test-k8s-controller
  #     - name: Get Capact CLI for linux
  #       run: |
  #         curl -Lo ./capact https://storage.googleapis.com/capactio-binaries/latest/capact_linux_amd64/capact
  #         chmod +x ./capact
  #     - id: 'auth'
  #       name: 'Authenticate to Google Cloud'
  #       uses: 'google-github-actions/auth@v1'
  #       with:
  #         token_format: 'access_token'
  #         credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
  #     - name: Login to GCR
  #       uses: docker/login-action@v2
  #       with:
  #         registry: gcr.io
  #         username: oauth2accesstoken
  #         password: ${{ steps.auth.outputs.access_token }}
  #     - name: Run cross-functional integration tests
  #       env:
  #         BUILD_IMAGES: "false"
  #         ARTIFACTS: "output/"
  #         DISABLE_MONITORING_INSTALLATION: "true"
  #         CAPACT_BINARY: "./capact"
  #         CLUSTER_TYPE: ${{ matrix.cluster }}
  #         DISABLE_K3D_REGISTRY: "true"
  #       run: |
  #         make test-integration
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v2
  #       if: ${{ always() }}
  #       with:
  #         name: cluster_dump_${{github.sha}}
  #         path: "output"
  #         retention-days: 5 # Default 90 days

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: SuperMaestro CI Notifier
          SLACK_COLOR: 'red'
          SLACK_TITLE: 'Message'
          SLACK_CHANNEL: 'pat-supermaestro-alert-notification'
          SLACK_MESSAGE: 'Main branch build failed :ahhhhhhhhh:'
          SLACK_ICON_EMOJI: ':this-is-fine:'
          SLACK_FOOTER: "Hopefully it is not an error, it's gorgeous feature"
          SLACK_WEBHOOK: ${{ secrets.SLACK_PRIV_DEV_TEAM_WEBHOOK }}
